// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';

// Pointing at the original Supabase project (outside Lovable Cloud) where the
// existing schema (profiles, user_permissions, employee, jobhistory, etc.) and
// users live. Anon key is safe to ship in the client.
const SUPABASE_URL = "https://vmqoyxhbvcuiesptnthg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcW95eGhidmN1aWVzcHRudGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2NzIxMjcsImV4cCI6MjA5MjI0ODEyN30.6hibfvVJBShlUAhTDLu_Au3aawwi05xCtS50b_9R7Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: Database typings are intentionally untyped here because the schema lives
// in an external Supabase project (not Lovable Cloud's auto-generated types).
export const supabase: SupabaseClient = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
