
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sglndmhreehyvslotves.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnbG5kbWhyZWVoeXZzbG90dmVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDc4ODQsImV4cCI6MjA1OTIyMzg4NH0.sxCdTuxgFeTUsz8FreMXzXRlfITUEa5XUrTb8K7d7F8";

const isBrowser = typeof window !== 'undefined';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    },
    auth: {
      persistSession: isBrowser,
      autoRefreshToken: isBrowser,
      storage: isBrowser ? localStorage : undefined,
      detectSessionInUrl: isBrowser ? false : undefined,
      flowType: 'implicit',
      debug: isBrowser ? true : false, // Enable debug mode for more auth logging in browser only
      onAuthStateChange: isBrowser ? (event, session) => {
        console.log("Supabase Auth Event:", event, session ? "Session exists" : "No session");
      } : undefined
    }
  }
);
